extends Object
class_name GlobalEnums

enum STATE {EGG, NEUTRAL, HAPPY, SICK, UPSET, RAN_AWAY}
enum DIFFICULTY {RELAXED, STANDARD, REALISTIC}
enum GENDER {GENDERLESS, MALE, FEMALE}
# NONE is an ErrorCode because 0 = success.
enum ERRORCODES {NONE, GENERIC, PREFORMANCE_FAILSAFE}
