extends Object
class_name GlobalEnums

enum ANIMATION_STATE {}
enum PET_STATE {EGG, NEUTRAL, HAPPY, LOVED, UPSET, SICK, RAN_AWAY}
enum PET_GENDER {GENDERLESS, MALE, FEMALE}
enum GAME_DIFFICULTY {RELAXED, STANDARD, REALISTIC}
# NONE is an ErrorCode because 0 = success.
enum ERROR_CODES {NONE, GENERIC, PREFORMANCE_FAILSAFE}
